### ISSUE TITLE
Package: `date-fns` should be dependency

### ISSUE THREAD

**Issue by dzsodzso63** [marklawlor/react-window-timeline#8]
There's a reference to `date-fns` package from the `dist`illed resource, so it should be dependency instead of dev dep.

**Comment by marklawlor** [comment]
Hi @dzsodzso63, can you provide me a stack trace of the error with the line number? `date-fns` shouldn't be part of the main package and should only be used for the examples. I've grepped my dist folder and was unable to find the `date-fns` package.

Also thanks for checking out this library, I'm open to feedback and happy to make improvements.

**Comment by marklawlor** [comment]
Hey @dzsodzso63, I've pushed a new version that removes `date-fns` as a runtime dependency.

Also thanks for checking out this library and please post any feedback as an issue. It was created for a particular use case so I'm interested to know how it works out for you. I would like this improve this library more as the other existing libraries all had issues that we were unable to work around.
